version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./build/:/usr/src/clean-node-api/build/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo